version: "3.8"

services:
  kfk01:
    hostname: "srvkfk01"
    build:
      context: "./kafka"
      dockerfile: "kraft.dockerfile"
    env_file:
      - kafka_cluster_id.env
      - srvkfk01.env
    volumes:
      - ${PWD}/datas/kfk01/config:/kafka/config
      - ${PWD}/datas/kfk01/logs:/kafka/logs
    ports:
      - "19092:9092"

  ui-01:
    profiles:
      - donotstart
    image: provectuslabs/kafka-ui
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    ports:
      - "18080:8080"
    volumes:
      - ./datas/ui-01/config.yml:/etc/kafkaui/dynamic_config.yaml

  ui-02:
    image: docker.redpanda.com/redpandadata/console
    environment:
      KAFKA_BROKERS: srvkfk01:9092
    ports:
      - "18080:8080"


