auth:
  type: LOGIN_FORM

spring:
  security:
    user:
      name: poc
      password: cop

kafka:
  clusters:
  - bootstrapServers: kfkbrksrc-00:9092,kfkbrksrc-01:9092
    name: KfkBrkSrc
    properties:
      security.protocol: SSL
      ssl.keystore.password: PwdJks
      ssl.keystore.location: /etc/kafkaui/jks/ca-src-kafka-ui.jks
    readOnly: false
    ssl:
      truststoreLocation: /etc/kafkaui/jks/ca-src.jks
      truststorePassword: PwdJks
  - bootstrapServers: kfkbrkdst-00:9092,kfkbrkdst-01:9092
    name: KfkBrkDst
    properties:
      security.protocol: SSL
      ssl.keystore.password: PwdJks
      ssl.keystore.location: /etc/kafkaui/jks/ca-dst-kafka-ui.jks
    readOnly: false
    ssl:
      truststoreLocation: /etc/kafkaui/jks/ca-dst.jks
      truststorePassword: PwdJks
    kafkaConnect:
      - address: http://kfkcnt-00:8083
        name: srvCntNode00
      - address: http://kfkcnt-01:8083
        name: srvCntNode01
rbac:
  roles: []
webclient: {}
